### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by modelga** [Pytlicek/MailgunMailer#4]
I've run the db_seed on collation latin1_swedish (my fault), so all tables with text inherit the collation from db. Would be great to have possibility (in config/seed file/environment) to set collation for created tables to avoid similar issues. Is it possible to do with SQL Alchemy?

**Comment by Pytlicek** [comment]
Maybe encoding in Engine Creation will help. I'm going to check and test it.

http://docs.sqlalchemy.org/en/latest/core/engines.html?highlight=encoding#sqlalchemy.create_engine.params.encoding

**Comment by modelga** [comment]
I have ride around the docs, and see only one place where this may be relevant: 

http://docs.sqlalchemy.org/en/latest/core/type_basics.html
To set a collation type on column definition.

**Comment by Pytlicek** [comment]
I tried it with column definition but without success.
When I used encoding=latin1 in connection url, it ends with : Failed processing pyformat-parameters; 'latin-1' codec can't encode character '\u013e' in position 4: ordinal not in range(256).
Maybe easiest way in this century is using same encoding as python3 uses :)
IMHO it isn't good pattern mixing-up encodings.

**Comment by modelga** [comment]
Might be. Would be great to have that info in README / Install file.
